version: "3.7"

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    external_links:
      - api:api
    ports:
      - 80:80
    networks:
      - project

networks:
  project:
    external: true